### ISSUE TITLE
[Feature] Add support for mapping mouse wheel actions

### ISSUE THREAD

**Issue by strycore** [ShadowBlip/InputPlumber#257]
The default Mouse / WASD profile has an example of mapping the mouse wheel to gamepad button but these mappings aren't implemented  yet.

```
  # Bumpers
  - name: RB
    source_event:
      gamepad:
        button: RightBumper
    target_events:
      - mouse:
          button: WheelUp

  - name: LB
    source_event:
      gamepad:
        button: LeftBumper
    target_events:
      - mouse:
          button: WheelDown
```
