### ISSUE TITLE
Creating Composite devices through D-Bus do not work

### ISSUE THREAD

**Issue by korewaChino** [ShadowBlip/InputPlumber#385]
Calling `CreateCompositeDevice` through D-Bus does not actually create a composite device, meanwhile creating the config file to load on startup creates it properly

## How to Reproduce

Use one of the default device presets (i.e the Switch Pro controller)

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/ShadowBlip/InputPlumber/main/rootfs/usr/share/inputplumber/schema/composite_device_v1.json
# Schema version number
version: 1
# The type of configuration schema
kind: CompositeDevice
# Name of the composite device mapping
name: Nintendo Co., Ltd. Pro Controller
# Maximum number of source devices per CompositeDevice.
maximum_sources: 1
# Only use this profile if *any* of the given matches matches. If this list is
# empty, then the source devices will *always* be checked.
# /sys/class/dmi/id/product_name
matches: []
# One or more source devices to combine into a single virtual device. The events
# from these devices will be watched and translated according to the key map.
source_devices:
  - group: gamepad
    evdev:
      name: Nintendo Co., Ltd. Pro Controller
      handler: event*
  #- group: imu
  #  evdev:
  #    name: Nintendo Co., Ltd. Pro Controller (IMU)
# The target input device(s) to emulate by default
target_devices:
  - gamepad #TODO: Nintendo controller target
  - mouse
  - keyboard
options:
  auto_manage: true
  persist: true
```

Save it to a file and then attempt to load it using the `busctl`

```bash
busctl call org.shadowblip.InputPlumber \
              /org/shadowblip/InputPlumber/Manager \
              org.shadowblip.InputManager \
              CreateCompositeDevice s $PWD/composite.yaml
```

## Expected Behavior

The interface returns a path to the new D-Bus object, and a `CompositeDevice` is created

```
s "/org/shadowblip/InputPlumber/CompositeDevice0"
```

## Actual behavior

The interface returns an empty string, and no composite device is created

The interface returns a path to the new D-Bus object, and a `CompositeDevice` is created

```
s ""
```

## Additional Notes

The same config loads fine if it was placed in the config directory and loaded on startup
